### ISSUE TITLE
Incorrect parsing of unquoted months

### ISSUE THREAD

**Issue by vext01** [sciunto-org/python-bibtexparser#152]
Here is a valid bibtex entry:

```
$ cat test.bib 
@book{cheney85numerical,
    title={Numerical methods and computing},
    author={Cheney, Ward and Kincaid, David},
    journal={Pacific Grove: California},
    year={1985},
    month=Apr,
}
```

bibtexparser fails to parse the month correctly:

```
$ python2.7 -c "from bibtexparser.bparser import BibTexParser; import sys; BibTexParser(sys.stdin.read())" < test.bib  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "bibtexparser/bparser.py", line 62, in __new__
    return parse(data, **args)
  File "bibtexparser/bparser.py", line 30, in parse
    return parser.parse(data)
  File "bibtexparser/bparser.py", line 130, in parse
    self._expr.parseFile(bibtex_file_obj)
  File "bibtexparser/bibtexexpression.py", line 251, in parseFile
    return self.main_expression.parseFile(file_obj, parseAll=True)
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 2144, in parseFile
    return self.parseString(file_contents, parseAll)
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 3900, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 3829, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 3900, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 3839, in parseImpl
    loc, tmptokens = self_expr_parse( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1405, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/usr/local/lib/python2.7/site-packages/pyparsing.py", line 1049, in wrapper
    ret = func(*args[limit[0]:])
  File "bibtexparser/bibtexexpression.py", line 248, in _string_expr_parse_action
    return self._string_expr_parse_action_fun(s, l, t)
  File "bibtexparser/bparser.py", line 162, in <lambda>
    self._interpolate_string_expression(t))
  File "bibtexparser/bparser.py", line 295, in _interpolate_string_expression
    return ''.join([self._expand_string(s) for s in string_expr])
  File "bibtexparser/bparser.py", line 306, in _expand_string
    return string_or_bibdatastring.get_value()
  File "bibtexparser/bibdatabase.py", line 122, in get_value
    return self._bibdatabase.expand_string(self.name)
  File "bibtexparser/bibdatabase.py", line 98, in expand_string
    raise(KeyError("Unknown string: {}.".format(name)))
KeyError: 'Unknown string: apr.'
```

Related #47.

**Comment by vext01** [comment]
This is with master btw.

**Comment by Phyks** [comment]
Closing, see https://github.com/sciunto-org/python-bibtexparser/issues/47#issuecomment-313850582.
