### ISSUE TITLE
Tutorial example returns bibtexparser.bibdatabase.UndefinedString

### ISSUE THREAD

**Issue by jeanluct** [sciunto-org/python-bibtexparser#222]
Ok, maybe I'm doing something stupid, but the most basic example in the [tutorial](https://bibtexparser.readthedocs.io/en/v1.0.1/tutorial.html) doesn't work for me.  Here's a minimal example:
```
import bibtexparser

bibtex_str = """@ARTICLE{Cesar2013,
  author = {Jean César},
  title = {An amazing title},
  year = {2013},
  month = jan,
  volume = {12},
  pages = {12--23},
  journal = {Nice Journal},
  abstract = {This is an abstract. This line should be long enough to test
     multilines...},
  comments = {A comment},
  keywords = {keyword1, keyword2}
}
"""

bib_database = bibtexparser.loads(bibtex_str)
```
and output
```
Traceback (most recent call last):
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 102, in expand_string
    self.strings[name])
KeyError: 'jan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bibtex_min.py", line 18, in <module>
    bib_database = bibtexparser.loads(bibtex_str)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/__init__.py", line 48, in loads
    return parser.parse(bibtex_str)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bparser.py", line 147, in parse
    self._expr.parseFile(bibtex_file_obj)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibtexexpression.py", line 263, in parseFile
    return self.main_expression.parseFile(file_obj, parseAll=True)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 2185, in parseFile
    return self.parseString(file_contents, parseAll)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3970, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3899, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3581, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3446, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3581, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3446, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3446, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3970, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3909, in parseImpl
    loc, tmptokens = self_expr_parse( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3446, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3768, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3446, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3581, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1428, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1072, in wrapper
    ret = func(*args[limit[0]:])
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibtexexpression.py", line 260, in _string_expr_parse_action
    return self._string_expr_parse_action_fun(s, l, t)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bparser.py", line 184, in <lambda>
    BibDataStringExpression.expression_if_needed(t)))
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bparser.py", line 178, in <lambda>
    maybe_interpolate = lambda expr: as_text(expr)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 223, in as_text
    return text_string_or_expression.get_value()
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 184, in get_value
    return ''.join([BibDataString.expand_string(s) for s in self.expr])
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 184, in <listcomp>
    return ''.join([BibDataString.expand_string(s) for s in self.expr])
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 150, in expand_string
    return string_or_bibdatastring.get_value()
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 131, in get_value
    return self._bibdatabase.expand_string(self.name)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 104, in expand_string
    raise(UndefinedString(name))
bibtexparser.bibdatabase.UndefinedString: 'jan'
```

Now, I kind of understand what's going on: the key `jan` is causing problem.  If I enclose it in braces the problem goes away.  But I'm wondering what's wrong with my installation, since this first example breaks right out of the box.  Any ideas?

Many thank.

**Comment by omangin** [comment]
Hi @jeanluct. You are right, the tutorial should not include an example that does not work.

The issue here is that the example with `month = jan` is not (by itself) correct Bibtex since it implies that a string definition exists for `jan`. To support the set of common strings used in Bibtex files (like the ones for months), to avoid that you can use the option `parser.common_strings = True` or the improvement to come from #205.

**Comment by jeanluct** [comment]
Ok, thanks.  I'll wait for the next release then, but I should point out that
```
import bibtexparser
from bibtexparser.bparser import BibTexParser

bibtex_str = """@ARTICLE{Cesar2013,
  author = {Jean César},
  title = {An amazing title},
  year = {2013},
  month = jan,
  volume = {12},
  pages = {12--23},
  journal = {Nice Journal},
  abstract = {This is an abstract. This line should be long enough to test
     multilines...},
  comments = {A comment},
  keywords = {keyword1, keyword2}
}
"""

parser = BibTexParser()
parser.common_strings = True

bib_database = bibtexparser.loads(bibtex_str,parser)
```
doesn't work for me either:
```
Traceback (most recent call last):
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 102, in expand_string
    self.strings[name])
KeyError: 'jan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bibtex_min.py", line 23, in <module>
    bib_database = bibtexparser.loads(bibtex_str,parser)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/__init__.py", line 48, in loads
    return parser.parse(bibtex_str)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bparser.py", line 147, in parse
    self._expr.parseFile(bibtex_file_obj)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibtexexpression.py", line 263, in parseFile
    return self.main_expression.parseFile(file_obj, parseAll=True)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 2185, in parseFile
    return self.parseString(file_contents, parseAll)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3970, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3899, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3581, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3446, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3581, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3446, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3446, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3970, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3909, in parseImpl
    loc, tmptokens = self_expr_parse( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3446, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3768, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3446, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 3581, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1428, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/home/jeanluc/.local/lib/python3.6/site-packages/pyparsing.py", line 1072, in wrapper
    ret = func(*args[limit[0]:])
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibtexexpression.py", line 260, in _string_expr_parse_action
    return self._string_expr_parse_action_fun(s, l, t)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bparser.py", line 184, in <lambda>
    BibDataStringExpression.expression_if_needed(t)))
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bparser.py", line 178, in <lambda>
    maybe_interpolate = lambda expr: as_text(expr)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 223, in as_text
    return text_string_or_expression.get_value()
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 184, in get_value
    return ''.join([BibDataString.expand_string(s) for s in self.expr])
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 184, in <listcomp>
    return ''.join([BibDataString.expand_string(s) for s in self.expr])
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 150, in expand_string
    return string_or_bibdatastring.get_value()
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 131, in get_value
    return self._bibdatabase.expand_string(self.name)
  File "/home/jeanluc/.local/lib/python3.6/site-packages/bibtexparser/bibdatabase.py", line 104, in expand_string
    raise(UndefinedString(name))
bibtexparser.bibdatabase.UndefinedString: 'jan'
```
Again, maybe I'm just doing something wrong...

**Comment by jeanluct** [comment]
Ah, ok, I understand now.  Many thanks for your work.
