### ISSUE TITLE
Error on empty file

### ISSUE THREAD

**Issue by juanmeleiro** [sciunto-org/python-bibtexparser#241]
There's an `IndexError: string index out of range` when trying to parse an empty file. I couldn't find a formal grammar for bibtex, so I can't tell if it's a bug. Intuitively, though, I think an empty file should yield an empty library, and not an error.

Funily enough (though not very surprisingly), there's no error for a file containing a single space, or a single newline.

* * *

The file `test.py` has contents

```python
import bibtexparser

with open(input('Path to empty file: '), 'r') as f:
    data = bibtexparser.load(f)
```

And then

```bash
$ touch test.bib
$ python3 test.py
Path to empty file: test
Traceback (most recent call last):
  File "bibtexparsertest.py", line 4, in <module>
    data = bibtexparser.load(f)
  File "/home/juanmeleiro/.local/lib/python3.6/site-packages/bibtexparser/__init__.py", line 71, in load
    return parser.parse_file(bibtex_file)
  File "/home/juanmeleiro/.local/lib/python3.6/site-packages/bibtexparser/bparser.py", line 177, in parse_file
    return self.parse(file.read(), partial=partial)
  File "/home/juanmeleiro/.local/lib/python3.6/site-packages/bibtexparser/bparser.py", line 153, in parse
    bibtex_file_obj = self._bibtex_file_obj(bibtex_str)
  File "/home/juanmeleiro/.local/lib/python3.6/site-packages/bibtexparser/bparser.py", line 225, in _bibtex_file_obj
    if bibtex_str[0] == byte:
IndexError: string index out of range
```

However,

```bash
$ printf ' ' > test
$ python3 test.py
Path to empty file: test
$
```

I don't know if empty files should be supported, but I think it's worth mentioning. Also, note that I only do not write a patch myself because I don't know how to write unit tests.

**Comment by MiWeiss** [comment]
I could not reproduce this. Maybe it only happens with old versions of `pyparsing`? 

Anyways, I added a test to cover this case. #303
