### ISSUE TITLE
bug when copying links with bibtex parser

### ISSUE THREAD

**Issue by gurudevdutt** [sciunto-org/python-bibtexparser#289]
Here is the code I used
`import logging
import logging.config
import bibtexparser
from bibtexparser.bparser import BibTexParser
# from bibtexparser.bwriter import BibTexWriter
# from bibtexparser.bibdatabase import BibDatabase
import bibtexparser.customization as bparsecustom
from pathlib import Path

logger = logging.getLogger(__name__)

logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s %(funcName)s:%(lineno)d: %(message)s'
        },
    },
    'handlers': {
        'default': {
            'level':'DEBUG',
            'formatter': 'standard',
            'class':'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['default'],
            'level': 'DEBUG',
            'formatter': 'standard',
            'propagate': True
        }
    }
})

def my_customizations(record):
    """Use some functions delivered by the library

    :param record: a record
    :returns: -- customized record
    """
    record = bparsecustom.type(record)
    #record = bparsecustom.author(record)
    record = bparsecustom.editor(record)
    record = bparsecustom.journal(record)
    record = bparsecustom.keyword(record)
    record = bparsecustom.link(record)
    record = bparsecustom.page_double_hyphen(record)
    record = bparsecustom.homogenize_latex_encoding(record)
    record = bparsecustom.doi(record)
    return record

def copy_bib_files_custom(file:Path,file2:Path):
    with open(file, 'r') as bibtex_file:
        parser = BibTexParser()
        parser.customization = my_customizations
        bib_database = bibtexparser.load(bibtex_file, parser=parser)
    with open(file2, 'w') as bibtex_file:
        bibtexparser.dump(bib_database, bibtex_file)

if __name__ == '__main__':
    bibtex = """@article{ WOS:000670704600001,
Author = {Afek, Gadi and Monteiro, Fernando and Wang, Jiaxiang and Siegel,
   Benjamin and Ghosh, Sumita and Moore, David C.},
Title = {{Limits on the abundance of millicharged particles bound to matter}},
Journal = {{PHYSICAL REVIEW D}},
Year = {{2021}},
Volume = {{104}},
Number = {{1}},
Month = {{JUL 7}},
DOI = {{10.1103/PhysRevD.104.012004}},
Article-Number = {{012004}},
ISSN = {{2470-0010}},
EISSN = {{2470-0029}},
ResearcherID-Numbers = {{Moore, David C/Q-2208-2017
   }},
ORCID-Numbers = {{Moore, David C/0000-0002-2358-4761
   Siegel, Benjamin/0000-0002-4943-5967
   Ghosh, Sumita/0000-0003-3502-0063}},
Unique-ID = {{WOS:000670704600001}},
} """
    directory = Path('/tmp')
    fname = 'bibtex.bib'
    fname2 = 'bibtex2.bib'
    file = directory / fname
    file2 = directory / fname2
    with open(fname, 'w') as bibfile:
        bibfile.write(bibtex)
    copy_bib_files_custom(fname,fname2)
    with open(fname2, 'r') as bibfile:
        bp = BibTexParser(bibfile.read())
        print(bp.get_entry_list())`

And here is the logging output:

2021-12-23 19:30:44,329 [DEBUG] bibtexparser.bparser action:31: Found Entry: ['article', 'WOS:000670704600001', {'Unique-ID': '{WOS:000670704600001}', 'ORCID-Numbers': '{Moore, David C/0000-0002-2358-4761\nSiegel, Benjamin/0000-0002-4943-5967\nGhosh, Sumita/0000-0003-3502-0063}', 'ResearcherID-Numbers': '{Moore, David C/Q-2208-2017\n}', 'EISSN': '{2470-0029}', 'ISSN': '{2470-0010}', 'Article-Number': '{012004}', 'DOI': '{10.1103/PhysRevD.104.012004}', 'Month': '{JUL 7}', 'Number': '{1}', 'Volume': '{104}', 'Year': '{2021}', 'Journal': '{PHYSICAL REVIEW D}', 'Title': '{Limits on the abundance of millicharged particles bound to matter}', 'Author': 'Afek, Gadi and Monteiro, Fernando and Wang, Jiaxiang and Siegel,\nBenjamin and Ghosh, Sumita and Moore, David C.'}]
2021-12-23 19:30:44,329 [DEBUG] bibtexparser.bparser _add_entry:286: Apply customizations and return dict
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: unique-id
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: orcid-numbers
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: researcherid-numbers
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: eissn
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: issn
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: article-number
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: doi
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: month
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: number
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: volume
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: year
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: journal
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: title
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:529: Protect uppercase in title
2021-12-23 19:30:44,335 [DEBUG] bibtexparser.customization homogenize_latex_encoding:530: Before: Limits on the abundance of millicharged particles bound to matter
2021-12-23 19:30:44,336 [DEBUG] bibtexparser.customization homogenize_latex_encoding:532: After: {L}imits on the abundance of millicharged particles bound to matter
2021-12-23 19:30:44,336 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: author
2021-12-23 19:30:44,336 [DEBUG] bibtexparser.customization homogenize_latex_encoding:526: Apply string_to_latex to: ENTRYTYPE
Traceback (most recent call last):
  File "/Users/gurudevdutt/PycharmProjects/fixbib/venv/lib/python3.7/site-packages/bibtexparser/bwriter.py", line 137, in _entry_to_bibtex
    value=_str_or_expr_to_bibtex(entry[field]))
  File "/Users/gurudevdutt/PycharmProjects/fixbib/venv/lib/python3.7/site-packages/bibtexparser/bwriter.py", line 30, in _str_or_expr_to_bibtex
    return '{' + e + '}'
TypeError: can only concatenate str (not "list") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gurudevdutt/Library/Application Support/JetBrains/PyCharm2021.1/scratches/scratch_12.py", line 94, in <module>
    copy_bib_files_custom(fname,fname2)
  File "/Users/gurudevdutt/Library/Application Support/JetBrains/PyCharm2021.1/scratches/scratch_12.py", line 64, in copy_bib_files_custom
    bibtexparser.dump(bib_database, bibtex_file)
  File "/Users/gurudevdutt/PycharmProjects/fixbib/venv/lib/python3.7/site-packages/bibtexparser/__init__.py", line 108, in dump
    bibtex_file.write(writer.write(bib_database))
  File "/Users/gurudevdutt/PycharmProjects/fixbib/venv/lib/python3.7/site-packages/bibtexparser/bwriter.py", line 93, in write
    bibtex += getattr(self, '_' + content + '_to_bibtex')(bib_database)
  File "/Users/gurudevdutt/PycharmProjects/fixbib/venv/lib/python3.7/site-packages/bibtexparser/bwriter.py", line 113, in _entries_to_bibtex
    bibtex += self._entry_to_bibtex(entry)
  File "/Users/gurudevdutt/PycharmProjects/fixbib/venv/lib/python3.7/site-packages/bibtexparser/bwriter.py", line 140, in _entry_to_bibtex
    % (field, entry['ID']))
TypeError: The field link in entry WOS:000670704600001 must be a string

Process finished with exit code 1

**Comment by MiWeiss** [comment]
I ran the following without any issues (`bibtexparser 1.2.0`, backed by `pyparsing 3.09`.

@gurudevdutt if you can still reproduce the issue, please provide a colab notebook showing the problem. Thanks.

```
import logging
import logging.config
import bibtexparser
from bibtexparser.bparser import BibTexParser

from bibtexparser.bwriter import BibTexWriter
from bibtexparser.bibdatabase import BibDatabase
import bibtexparser.customization as bparsecustom
from pathlib import Path

logger = logging.getLogger()

logging.config.dictConfig({
'version': 1,
'disable_existing_loggers': False,
'formatters': {
'standard': {
'format': '%(asctime)s [%(levelname)s] %(name)s %(funcName)s:%(lineno)d: %(message)s'
},
},
'handlers': {
'default': {
'level':'DEBUG',
'formatter': 'standard',
'class':'logging.StreamHandler',
},
},
'loggers': {
'': {
'handlers': ['default'],
'level': 'DEBUG',
'formatter': 'standard',
'propagate': True
}
}
})

def my_customizations(record):
  """Use some functions delivered by the library

  :param record: a record
  :returns: -- customized record
  """
  record = bparsecustom.type(record)
  # record = bparsecustom.author(record)
  record = bparsecustom.editor(record)
  record = bparsecustom.journal(record)
  record = bparsecustom.keyword(record)
  record = bparsecustom.link(record)
  record = bparsecustom.page_double_hyphen(record)
  record = bparsecustom.homogenize_latex_encoding(record)
  record = bparsecustom.doi(record)
  return record

def copy_bib_files_custom(file1:Path,file2:Path):
  with open(file1) as bibtex_file:
      parser = BibTexParser()
      parser.customization = my_customizations
      bib_database = bibtexparser.load(bibtex_file)
      print(bib_database.entries)
  with open(file2, 'w') as bibtex_file:
    bibtexparser.dump(bib_database, bibtex_file)


bibtex = """@Article{ WOS:000670704600001,
Author = {Afek, Gadi and Monteiro, Fernando and Wang, Jiaxiang and Siegel,
Benjamin and Ghosh, Sumita and Moore, David C.},
Title = {{Limits on the abundance of millicharged particles bound to matter}},
Journal = {{PHYSICAL REVIEW D}},
Year = {{2021}},
Volume = {{104}},
Number = {{1}},
Month = {{JUL 7}},
DOI = {{10.1103/PhysRevD.104.012004}},
Article-Number = {{012004}},
ISSN = {{2470-0010}},
EISSN = {{2470-0029}},
ResearcherID-Numbers = {{Moore, David C/Q-2208-2017
}},
ORCID-Numbers = {{Moore, David C/0000-0002-2358-4761
Siegel, Benjamin/0000-0002-4943-5967
Ghosh, Sumita/0000-0003-3502-0063}},
Unique-ID = {{WOS:000670704600001}},
} """

fname = 'bibtex.bib'
fname2 = 'bibtex2.bib'

with open(fname, 'w') as bibfile:
  bibfile.write(bibtex)
copy_bib_files_custom(fname,fname2)

with open(fname2, 'r') as bibfile:
  bp = BibTexParser(bibfile.read())
  print(bp.get_entry_list())
```
