### ISSUE TITLE
parse error with no useful output

### ISSUE THREAD

**Issue by keithbriggs** [sciunto-org/python-bibtexparser#75]
I get output this on a .bib file which has no syntax errors according to bibtex.    How do I figure out which line in the .bib file is causing this?

2015-08-05 14:21:25,893 [DEBUG] bibtexparser.bparser _parse_records:157: Inspect line 0
2015-08-05 14:21:25,893 [DEBUG] bibtexparser.bparser _parse_records:157: Inspect line 1
2015-08-05 14:21:25,894 [DEBUG] bibtexparser.bparser _parse_records:157: Inspect line 2
2015-08-05 14:21:25,894 [DEBUG] bibtexparser.bparser _parse_records:161: Line starts with @
2015-08-05 14:21:25,894 [DEBUG] bibtexparser.bparser _add_parsed_record:143: The record is not empty. Let's parse it.
2015-08-05 14:21:25,894 [DEBUG] bibtexparser.bparser _parse_record:190: The record does not start with @. Return empty dict.
2015-08-05 14:21:25,894 [DEBUG] bibtexparser.bparser _add_parsed_record:149: Nothing returned from the parsed record!
2015-08-05 14:21:25,894 [DEBUG] bibtexparser.bparser _parse_records:165: The record is set to empty
2015-08-05 14:21:25,894 [DEBUG] bibtexparser.bparser _parse_records:157: Inspect line 3
2015-08-05 14:21:25,894 [DEBUG] bibtexparser.bparser _parse_records:161: Line starts with @
2015-08-05 14:21:25,894 [DEBUG] bibtexparser.bparser _add_parsed_record:143: The record is not empty. Let's parse it.
2015-08-05 14:21:25,894 [DEBUG] bibtexparser.bparser _parse_record:226: The record startswith @string
Traceback (most recent call last):
  File "./try_bibtexparser.py", line 43, in <module>
    dump('../bibtex/misc_place_names.bib')
  File "./try_bibtexparser.py", line 38, in dump
    bib_database=bibtexparser.loads(bibtex_str)
  File "/usr/local/lib/python3.4/dist-packages/bibtexparser/__init__.py", line 43, in loads
    return parser.parse(bibtex_str)
  File "/usr/local/lib/python3.4/dist-packages/bibtexparser/bparser.py", line 119, in parse
    self._parse_records(customization=self.customization)
  File "/usr/local/lib/python3.4/dist-packages/bibtexparser/bparser.py", line 163, in _parse_records
    _add_parsed_record(record, records)
  File "/usr/local/lib/python3.4/dist-packages/bibtexparser/bparser.py", line 144, in _add_parsed_record
    parsed = self._parse_record(record, customization=customization)
  File "/usr/local/lib/python3.4/dist-packages/bibtexparser/bparser.py", line 227, in _parse_record
    key, val = [i.strip().strip('{').strip('}').replace('\n', ' ') for i in record.split('{', 1)[1].strip('\n').strip(',').strip('}').split('=')]
IndexError: list index out of range

**Comment by sciunto** [comment]
This is the kind of arrogant comment that does not encourage me to help and develop. I'm closing.

**Comment by keithbriggs** [comment]
The parser crashes and I like to figure out why. I turned on the logging, which looks like it's indicating a problem in line 3, but I can't see a problem there. It seems to be due to @string definitions, as other files wihout these parse correctly.


Keith



________________________________

**Comment by keithbriggs** [comment]
I figured it out - @string definitions cause the parser to crash when some text follows the closing “}”.   The following text gets included in the record.

Keith
